language: cpp
compiler: gcc
before_install:
  - sudo apt-get update
install: 
  - cd Code/Angel 
  - sudo ./nix-prereqs.sh
  - cd ..
script:
  - cd ClientGame
  - make
  - cd ../IntroGame
  - make

notifications:
  email:
    on_success: change
    on_failure: change
